
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="MIT License"
[[mods]] #mandatory
    modId="jsg_milkyway" #mandatory
    version="1.0.0.0" #mandatory
    displayName="Just Stargate Mod: MilkyWay" #mandatory
    displayURL="https://justsgmod.eu/" #optional
    logoFile="mod.png" #optional
    authors="MineDragonCZ_, matousss, frfole" #optional
    description='''MilkyWay addon for Just Stargate Mod.\nNeeds JSG: Core mod.'''


[[dependencies.jsg_milkyway]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.jsg_milkyway]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
