
modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="MIT License"
[[mods]] #mandatory
    modId="jsg_@MODID@" #mandatory
    version="@VERSION@" #mandatory
    displayName="Just Stargate Mod: @MODNAME@" #mandatory
    displayURL="https://justsgmod.eu/" #optional
    logoFile="mod.png" #optional
    authors="@AUTHORS@" #optional
    description='''
    @DESCRIPTION@
    '''


[[dependencies.jsg@MODID@]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.jsg@MODID@]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"

# -----------------------------
# INCLUDING CORE MOD
# -----------------------------
[[dependencies.jsgcore]]
    modId="jsg-core"
    mandatory=true
    versionRange="[1.0.0.0,)"
    ordering="NONE"
    side="BOTH"
